#!/usr/bin/env python3
"""Embed an STL into mesh.js as base64 float32 positions, for the previz.

The layout page has to stay a single self-contained file, so the mesh travels
inline rather than being fetched. STL carries no shared vertices, so this just
hands three.js a flat position array and lets it compute normals.

    python3 make_mesh.py path/to/78-decimated.stl
    python3 make_mesh.py path/to/model.stl --budget 40000   # cap triangles

Writes mesh.js next to this script. Re-run build.py afterwards.
"""

import argparse
import base64
import pathlib
import struct
import sys

ROOT = pathlib.Path(__file__).parent
OUT = ROOT / 'mesh.js'


def read_stl(path: pathlib.Path):
    """Return a flat list of floats (9 per triangle). Handles binary and ASCII."""
    raw = path.read_bytes()

    # ASCII STLs start with "solid" AND contain "facet normal"; binary files can
    # begin with "solid" too, so the header alone is not a reliable test.
    if raw[:5].lower() == b'solid' and b'facet normal' in raw[:2048]:
        verts = []
        for line in raw.decode('utf-8', 'replace').splitlines():
            parts = line.split()
            if len(parts) == 4 and parts[0] == 'vertex':
                verts.extend(float(v) for v in parts[1:4])
        if len(verts) % 9:
            raise SystemExit(f'ASCII STL vertex count not a multiple of 3: {len(verts)//3}')
        return verts

    if len(raw) < 84:
        raise SystemExit('file too short to be a binary STL')
    (count,) = struct.unpack('<I', raw[80:84])
    expect = 84 + count * 50
    if len(raw) < expect:
        raise SystemExit(f'binary STL truncated: header says {count} triangles, '
                         f'needs {expect} bytes, file is {len(raw)}')

    verts = []
    off = 84
    for _ in range(count):
        # 12 floats per facet: normal (3) + three vertices (9), then uint16 attr
        vals = struct.unpack_from('<12f', raw, off)
        verts.extend(vals[3:12])
        off += 50
    return verts


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('stl', type=pathlib.Path)
    ap.add_argument('--budget', type=int, default=60000,
                    help='max triangles to keep (uniform stride, not a real decimate)')
    ap.add_argument('--name', default='decimated')
    args = ap.parse_args()

    if not args.stl.exists():
        raise SystemExit(f'no such file: {args.stl}')

    verts = read_stl(args.stl)
    tris = len(verts) // 9
    print(f'  {args.stl.name}: {tris:,} triangles')

    if tris > args.budget:
        # crude but honest: keep every Nth triangle. If this ever shows, the
        # source needs a real decimate (meshlab/blender) rather than a stride.
        stride = tris // args.budget + 1
        kept = [v for i in range(0, tris, stride) for v in verts[i * 9:(i + 1) * 9]]
        print(f'  over budget - keeping every {stride}th -> {len(kept)//9:,} triangles')
        verts = kept

    import array
    buf = array.array('f', verts)
    if sys.byteorder != 'little':
        buf.byteswap()
    b64 = base64.b64encode(buf.tobytes()).decode()

    OUT.write_text(
        '/* Generated by make_mesh.py - do not edit by hand. */\n'
        f'window.MESH = {{ name: {args.name!r}, tris: {len(verts)//9}, '
        f'positions: "{b64}" }};\n',
        encoding='utf-8')
    print(f'\n  mesh.js  {OUT.stat().st_size / 1024:.1f} KB  '
          f'({len(verts)//9:,} triangles)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
