#!/usr/bin/env python3
"""Embed cv-draw renders into prints.js as small JPEG data URIs.

The layout previz hangs real artwork on the object wall rather than grey
placeholder rectangles, and it has to stay a single self-contained file, so the
images travel inline. Thumbnails only - 420px wide is plenty at previz scale
and keeps the whole page under a megabyte.

    python3 make_prints.py
"""

import base64
import io
import json
import pathlib
import sys

from PIL import Image

CV_DRAW = pathlib.Path.home() / 'sandbox' / 'dnuke-art' / 'cv-draw' / 'out'
OUT = pathlib.Path(__file__).parent / 'prints.js'

PICKS = ['raytrace', 'terrain', 'flowfield', 'stainedglass', 'topo']
THUMB_W = 420
QUALITY = 74


def main() -> int:
    if not CV_DRAW.is_dir():
        raise SystemExit(f'cv-draw output not found: {CV_DRAW}')

    data = {}
    for name in PICKS:
        src = CV_DRAW / f'{name}.png'
        if not src.exists():
            print(f'  skip {name} (no {src.name}) - rerun cv-draw first')
            continue

        im = Image.open(src).convert('RGB')
        w, h = im.size
        thumb = im.resize((THUMB_W, max(1, round(h * THUMB_W / w))), Image.LANCZOS)

        buf = io.BytesIO()
        thumb.save(buf, 'JPEG', quality=QUALITY, optimize=True)
        blob = buf.getvalue()

        data[name] = {
            'aspect': round(w / h, 4),
            'uri': 'data:image/jpeg;base64,' + base64.b64encode(blob).decode(),
        }
        print(f'  {name:<14} {w}x{h}  aspect {w / h:.3f}  ->{len(blob) / 1024:6.1f} KB')

    if not data:
        raise SystemExit('nothing embedded')

    OUT.write_text(
        '/* Generated by make_prints.py - do not edit by hand. */\n'
        'window.PRINTS = ' + json.dumps(data, indent=0) + ';\n',
        encoding='utf-8',
    )
    print(f'\n  {OUT.name}  {OUT.stat().st_size / 1024:.1f} KB')
    return 0


if __name__ == '__main__':
    sys.exit(main())
